Implement express-heroku
4meridian/bookshelf pull request #11
Opened 2021-01-03 13:02 UTC by preveenraj

Implemented express with heroku.
@vishnuprasad-95 @ajayesivan

2021-01-11 07:51 UTC, vishnuprasad-95 approved these changes

2021-01-24 13:52 UTC, ajayesivan requested changes

2021-01-24 13:52 UTC, ajayesivan commented on Procfile
> +web: node server/bin/www
What is this file for? What does this command do?

2021-01-24 13:52 UTC, ajayesivan commented on assets.json
> +{"main":{"js":"bundle.js"}}
What is this file for?

2021-01-24 13:52 UTC, ajayesivan commented on package.json
> +  "name": "wheel.js",
The project name should be bookshelf

2021-01-24 13:52 UTC, ajayesivan commented on package.json
> +  "repository": "https://github.com/bigbinary/wheel.js.git",
Change repo & author

2021-01-24 13:52 UTC, ajayesivan commented on package.json
> -  "husky": {
Why removing husky?

2021-01-25 04:42 UTC, preveenraj commented on assets.json
> +{"main":{"js":"bundle.js"}}
it is an autogenerated file with the help of [AssetsPlugin](https://www.npmjs.com/package/assets-webpack-plugin)
Why is it used for? To dynamically generate paths of assets in our app in a json file.
and we can use that json file anywhere like our views embed the bundle into it.
@ajayesivan

2021-01-25 04:46 UTC, preveenraj commented on package.json
> -  "husky": {
removed by mistake, brought back. thanks for the care observation.

2021-01-25 07:28 UTC, ajayesivan commented on assets.json
> +{"main":{"js":"bundle.js"}}
Why we need an autogenerated file in git?

2021-01-25 13:53 UTC, preveenraj commented on assets.json
> +{"main":{"js":"bundle.js"}}
yes, but without that file, for the first time a developer runs the app, his app will crash. He should stop the app and run it again to make it work. Thats a cumbersome step. Do we need to ignore it still? @ajayesivan

2021-01-25 14:01 UTC, ajayesivan commented on assets.json
> +{"main":{"js":"bundle.js"}}
Git's not a place for generated files. So I feel you should remove it from git & do something to generate it when building the project and if that's not possible we can keep it.

2021-01-25 14:03 UTC, ajayesivan commented on assets.json
> +{"main":{"js":"bundle.js"}}
@preveenraj I will merge now. Any way you check how to properly handle it.

2021-01-25 14:03 UTC, ajayesivan approved these changes

2021-01-25 14:03 UTC, merged

2021-01-25 14:10 UTC, preveenraj commented on assets.json
> +{"main":{"js":"bundle.js"}}
odikko kandam vazhi. sheri nokaam @ajayesivan